name: Convert FIT to JSON

permissions:
  contents: write

on:
  push:
    paths:
      - 'fits/**/*.fit'      # se ejecuta al push de .fit dentro de fits/
  workflow_dispatch: {}

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fitparse

      - name: Convert all FIT files to JSON
        shell: bash
        run: |
          shopt -s globstar nullglob
          mkdir -p converted_json
          found=false
          for f in fits/**/*.fit; do
            found=true
            # Extrae subcarpeta (por ejemplo: 2025)
            subdir=$(dirname "${f#fits/}")
            mkdir -p "converted_json/${subdir}"
            out="converted_json/${subdir}/$(basename "${f%.*}").json"
            echo "Convirtiendo $f -> $out"
            python .github/scripts/convert_fit_to_json.py "$f" "$out"
            git add "$out"
          done
          if [ "$found" = false ]; then
            echo "No FIT files found"
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Converted FIT -> JSON (ci)" || echo "no changes to commit"
          git push || echo "push failed"
